### ISSUE TITLE
What is the purpose and function of the CSV files?

### ISSUE THREAD

**Issue by eabase** [JafferWilson/MT4-Ticks-To-MT5#5]
* What is the intended purpose and function of the CSV files?
   - Do they store the tick or candle data?
   - Are they used to reload old data when starting up?
* Are the CSV files created and stored in both MT4 and MT5 sides?

**Comment by JafferWilson** [comment]
1. What is the intended purpose and function of the CSV files?

- Do they store the tick or candle data?
Yes. .hst is the history files for MT4 symbols.
- Are they used to reload old data when starting up?
Yes. Any symbol needs history. Otherwise, they will start with candle 0 and you might have to wait for the candles to get filled in your chart before your try some analysis.

2. Are the CSV files created and stored in both MT4 and MT5 sides?
No. Only MT4. For the history purpose.

Please close this issue if satisfied.
